### ISSUE TITLE
The example code cannot run properly

### ISSUE THREAD

**Issue by zhengger** [dandao2022/swapbot#1]
Code example:
```tyepscript
import { fastGetPrice } from "dandao";
async function main (): Promise<void>
{

    let price = await fastGetPrice( "0x6B175474E89094C44Da98b954EedeAC495271d0F", 1 );
    console.log( price );

}

main().then();
```

Issue:
```log
Debugger listening on ws://127.0.0.1:53448/d55e24e9-d97c-41c3-8fcd-0d428422a340
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
/root/apps/tgbot/node_modules/dandao/build/main.js:8373
                if (block?.transactions?.length) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/root/apps/tgbot/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/apps/tgbot/src/btc1mm.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
Waiting for the debugger to disconnect...
```

Environment: Ubuntu 22.04 x64

**Comment by dandao2022** [comment]
Is the network status not working? 
![微信图片_20231007091642](https://github.com/dandao2022/swapbot/assets/40421988/bed35b4c-c12b-40d5-9333-1c4603141ffb)

**Comment by SteOnChain** [comment]
@dandao2022 is it possible to have a English translation and more advance setup guide please
